### ISSUE TITLE
get_user failing

### ISSUE THREAD

**Issue by christopher-dG** [khazhyk/osuapi#20]
I'll look into this a bit more when I have time but here's a stack trace:

```python
>>> osu = osuapi.OsuApi(k, connector=osuapi.ReqConnector())
>>> p = osu.get_user("cookiezi")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/degraafc/code/osu-bot/venv/lib/python3.6/site-packages/osuapi/osu.py", line 51, in get_user
    ), JsonList(User))
  File "/home/degraafc/code/osu-bot/venv/lib/python3.6/site-packages/osuapi/osu.py", line 31, in _make_req
    return self.connector.process_request(endpoint, {k: v for k, v in data.items() if v is not None}, type_)
  File "/home/degraafc/code/osu-bot/venv/lib/python3.6/site-packages/osuapi/connectors.py", line 98, in process_request
    return type_(resp.json())
  File "/home/degraafc/code/osu-bot/venv/lib/python3.6/site-packages/osuapi/dictmodel.py", line 67, in _
    return [oftype(entry) for entry in lst]
  File "/home/degraafc/code/osu-bot/venv/lib/python3.6/site-packages/osuapi/dictmodel.py", line 67, in <listcomp>
    return [oftype(entry) for entry in lst]
  File "/home/degraafc/code/osu-bot/venv/lib/python3.6/site-packages/osuapi/dictmodel.py", line 51, in __init__
    setattr(self, attr.field_name, attr.parse(v))
  File "/home/degraafc/code/osu-bot/venv/lib/python3.6/site-packages/osuapi/dictmodel.py", line 20, in parse
    return self.type(value)
  File "/home/degraafc/code/osu-bot/venv/lib/python3.6/site-packages/osuapi/dictmodel.py", line 67, in _
    return [oftype(entry) for entry in lst]
  File "/home/degraafc/code/osu-bot/venv/lib/python3.6/site-packages/osuapi/dictmodel.py", line 67, in <listcomp>
    return [oftype(entry) for entry in lst]
  File "/home/degraafc/code/osu-bot/venv/lib/python3.6/site-packages/osuapi/dictmodel.py", line 51, in __init__
    setattr(self, attr.field_name, attr.parse(v))
  File "/home/degraafc/code/osu-bot/venv/lib/python3.6/site-packages/osuapi/dictmodel.py", line 20, in parse
    return self.type(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
>>> osuapi.__version__
'0.0.28'
>>> sys.version
'3.6.5 (default, May 11 2018, 04:00:52) \n[GCC 8.1.0]'
```

**Comment by christopher-dG** [comment]
Ah, it's from events that aren't associated with beatmaps.

Here I just printed out what fields were being converted to what type.
```
ATTR: display_html
VALUE: <b><a href='/users/124493'>Cookiezi</a></b> has received the gift of osu! supporter!
TYPE: <class 'str'>
ATTR: beatmap_id
VALUE: None
TYPE: <class 'int'>
```
